### ISSUE TITLE
v5.0.0-alpha.7 - 'MLSwitch' object has no attribute 'namespace'

### ISSUE THREAD

**Issue by jeakob** [krahabb/meross_lan#383]
## Version of the custom_component

v5.0.0-alpha.7. Everything works on v5.0.0-alpha.4

Logs:

```
'MLSwitch' object has no attribute 'namespace'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/meross_lan/meross_entity.py", line 291, in async_turn_on
    await self.async_request_onoff(1)
  File "/config/custom_components/meross_lan/meross_entity.py", line 297, in async_request_onoff
    assert self.namespace
           ^^^^^^^^^^^^^^
AttributeError: 'MLSwitch' object has no attribute 'namespace'
```

## Describe the bug
Attempting to control the device results in the following error: 
Failed to call service switch/turn_on. 'MLSwitch' object has no attribute 'namespace'

Affecting the following:

mss426 4.0.0
Firmware: 4.1.1
Hardware: 4.0.0

**Comment by krahabb** [comment]
Hello @jeakob,
Thank your for signalling!

**Comment by rkozlik** [comment]
> ## Version of the custom_component
> v5.0.0-alpha.7. Everything works on v5.0.0-alpha.4
> 
> Logs:
> 
> ```
> 'MLSwitch' object has no attribute 'namespace'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
>     response = await hass.services.async_call(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
>     return await service.entity_service_call(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/config/custom_components/meross_lan/meross_entity.py", line 291, in async_turn_on
>     await self.async_request_onoff(1)
>   File "/config/custom_components/meross_lan/meross_entity.py", line 297, in async_request_onoff
>     assert self.namespace
>            ^^^^^^^^^^^^^^
> AttributeError: 'MLSwitch' object has no attribute 'namespace'
> ```
> 
> ## Describe the bug
> Attempting to control the device results in the following error: Failed to call service switch/turn_on. 'MLSwitch' object has no attribute 'namespace'
> 
> Affecting the following:
> 
> mss426 4.0.0 Firmware: 4.1.1 Hardware: 4.0.0

This issue also applies to mss810, mss120, mss620 and msg100

**Comment by Dodoww** [comment]
> ## Version of the custom_component
> v5.0.0-alpha.7. Everything works on v5.0.0-alpha.4
> 
> Logs:
> 
> ```
> 'MLSwitch' object has no attribute 'namespace'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
>     response = await hass.services.async_call(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
>     return await service.entity_service_call(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/config/custom_components/meross_lan/meross_entity.py", line 291, in async_turn_on
>     await self.async_request_onoff(1)
>   File "/config/custom_components/meross_lan/meross_entity.py", line 297, in async_request_onoff
>     assert self.namespace
>            ^^^^^^^^^^^^^^
> AttributeError: 'MLSwitch' object has no attribute 'namespace'
> ```
> 
> ## Describe the bug
> Attempting to control the device results in the following error: Failed to call service switch/turn_on. 'MLSwitch' object has no attribute 'namespace'
> 
> Affecting the following:
> 
> mss426 4.0.0 Firmware: 4.1.1 Hardware: 4.0.0


Same issue with MSS310, Firmware 6.3.22 Hardware 6.0.0

**Comment by fuomag9** [comment]
Same issue with mss315

**Comment by nutbox76** [comment]
Hi
I am having this problem also i have a MSS426 and a MSS420F that i get this with and i also MSS426 that is connected via homekit and is working fine .
This has started since updating to the latest meross lan firmware V5.0.0-alpha.7

**Comment by krahabb** [comment]
Yep, confirming this is a 'strong' issue in V5.0.0-alpha.7 for any 'toggle like' entity.
A beta release is on the way
