### ISSUE TITLE
Error: cannot import name 'SupportsResponse' from 'homeassistant.core' - after upgrade to v.4.4.1 from v3.3.0

### ISSUE THREAD

**Issue by ontirius** [krahabb/meross_lan#345]
Hi,
today I proced with upgrade to to v.4.4.1 from v3.3.0 of Custom Component Meross LAN

HACS Version: 1.33.0
HA Version: 2023.6.3

I'm using Meross LAN to manage in HA this Meross devices: mss310, mss310x and mss425ex.

Before the upgrade, all works properly, but after the upgared the Custom Component is not load for this error:

2023-12-07 14:56:09.441 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration meross_lan: Unable to import component: cannot import name 'SupportsResponse' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

![image](https://github.com/krahabb/meross_lan/assets/21127266/ed21f103-c871-4b3c-be85-b9e6c84d7224)

Could you help me to fix that error?

Many thanks for your patience
Best regard
Giuseppe

**Comment by ontirius** [comment]
Hi Krahabb,
many thanks for your support! Fixed with upgrade to HA 2023.9.2!
Best regards
Giuseppe
