### ISSUE TITLE
HA Version 2023.8.0 Beta breaks integration

### ISSUE THREAD

**Issue by TheOneOgre** [krahabb/meross_lan#304]
## Version of the custom_component
4.2.0

## Describe the bug
Devices no longer available/connecting

~~As per https://github.com/albertogeniola/meross-homeassistant, `In the past 24 hours, Meross has changed the signature of its HTTP API version (keeping the same API version in place). That did break every HomeAssistant integration version below 1.2.6 (included). In order to solve the issue, you should upgrade to version 1.2.8 which includes the necessary changes to work again with the updated version of the Meross APIs.`~~

~~This seems to have affected Meross LAN as well.~~

HA beta update 2023.8 seems to have broken the integration.

**Comment by krahabb** [comment]
Hello @TheOneOgre,
It looks like this issue was raised back in december and related to the @albertogeniola custom component. This wasn't affecting meross_lan at the time nor it should affect it now.
Are you experiencing any issue so far?

**Comment by TheOneOgre** [comment]
> Hello @TheOneOgre, It looks like this issue was raised back in december and related to the @albertogeniola custom component. This wasn't affecting meross_lan at the time nor it should affect it now. Are you experiencing any issue so far?

Interesting, I guess maybe coincidence that it broke for me and I saw that haha. Yeah my meross garage opener msg100 just disconnected and is not being discovered by the integration anymore. The meross cloud iot one however is functioning perfectly fine however.

I will post debug logs when I get home today.

**Comment by TheOneOgre** [comment]
So I completely reinstalled the integration, power cycled my device, and it was detected, key was pulled for the device and it finished the config flow, but then immediately dropped into "failed to set-up" Here is the log:
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/meross_lan/meross_device.py:578
Integration: Meross LAN (documentation, issues)
First occurred: 3:14:16 PM (2 occurrences)
Last logged: 3:18:49 PM

Error setting up entry msg100 - redact for meross_lan
Traceback (most recent call last):
  File "/config/custom_components/meross_lan/helpers.py", line 586, in exception_warning
    yield
  File "/config/custom_components/meross_lan/meross_device.py", line 183, in __init__
    device_registry.async_get(ApiProfile.hass).async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 479, in async_get_or_create
    device_info_type = _validate_device_info(config_entry, device_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 141, in _validate_device_info
    raise DeviceInfoError(
homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'connections': {('mac', '48:e1:e9:69:6f:5c')}, 'default_manufacturer': 'Meross', 'default_name': 'Smart Garage Door (redact)', 'identifiers': {('meross_lan', 'redact')}, 'model': 'msg100 3.5.0', 'sw_version': '3.2.5', 'via_device': None} for 'meross_lan' config entry: device info needs to either describe a device, link to existing device or provide extra information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/__init__.py", line 516, in async_setup_entry
    device = api.build_device(config_entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/__init__.py", line 402, in build_device
    device = class_type(descriptor, config_entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/switch.py", line 50, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/cover.py", line 495, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/meross_device.py", line 351, in __init__
    super().__init__(
  File "/config/custom_components/meross_lan/meross_device.py", line 181, in __init__
    with self.exception_warning("DeviceRegistry.async_get_or_create"):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/config/custom_components/meross_lan/helpers.py", line 588, in exception_warning
    self.warning(
  File "/config/custom_components/meross_lan/meross_device.py", line 470, in warning
    LOGGER.warning(f"MerossDevice({self.name}): {msg}", *args, **kwargs)
                                   ^^^^^^^^^
  File "/config/custom_components/meross_lan/meross_device.py", line 207, in name
    return self._get_internal_name()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/meross_device.py", line 578, in _get_internal_name
    return self.descriptor.productname
           ^^^^^^^^^^^^^^^
AttributeError: 'ToggleXMixinGarageMixinMerossDevice' object has no attribute 'descriptor'
`

**Comment by krahabb** [comment]
Which versions of HA and Python are you running it on?

**Comment by TheOneOgre** [comment]
> Which versions of HA and Python are you running it on? It looks to me that you are running on 2023.8 beta and I guess that code is rather unstable right now... I'm having a look to possible breaking changes anyway in order to prepare and maybe update meross_lan before the beta goes to release ;)

Indeed it is the beta/dev branch version: 2023.8.0.dev20230717

I am not sure what version of Python, whatever this version of HA ships with haha

**Comment by thomsy81** [comment]
Also experiencing the same issue on the beta

**Comment by RobertD502** [comment]
Just answer the question regarding python version - it is 3.11. Support for 3.10 is dropped in HA 2023.8

**Comment by townsmcp** [comment]
I have the same issues here on 2023.8.0b1. Getting 'Failed to setup' for a MSS426 (6 gang extension) and MSS210 (single socket)

**Comment by purcell-lab** [comment]
Failure with 2023.8.b as well;

Some more log data:

```
This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:588
Integration: Meross LAN (documentation, issues)
First occurred: 1:35:55 PM (4 occurrences)
Last logged: 1:37:14 PM

MerossDevice(Microwave): DeviceInfoError(Invalid device info {'connections': {('mac', '48:e1:e9:22:70:98')}, 'default_manufacturer': 'Meross', 'default_name': 'Smart Plug (20062974313169251h5048e1e9227098)', 'identifiers': {('meross_lan', '20062974313169251h5048e1e9227098')}, 'model': 'mss310 2.0.0', 'sw_version': '2.1.16', 'via_device': None} for 'meross_lan' config entry: device info needs to either describe a device, link to existing device or provide extra information.) in DeviceRegistry.async_get_or_create
MerossDevice(Fergus Ambient Light): DeviceInfoError(Invalid device info {'connections': {('mac', '48:e1:e9:1d:8f:3c')}, 'default_manufacturer': 'Meross', 'default_name': 'Smart Light (2005289271243390814348e1e91d8f3c)', 'identifiers': {('meross_lan', '2005289271243390814348e1e91d8f3c')}, 'model': 'msl420 2.0.0', 'sw_version': '2.1.11', 'via_device': None} for 'meross_lan' config entry: device info needs to either describe a device, link to existing device or provide extra information.) in DeviceRegistry.async_get_or_create
MerossDevice(Kitchen Smart Light): DeviceInfoError(Invalid device info {'connections': {('mac', '48:e1:e9:1d:8d:4e')}, 'default_manufacturer': 'Meross', 'default_name': 'Smart Light (2005282443310490814348e1e91d8d4e)', 'identifiers': {('meross_lan', '2005282443310490814348e1e91d8d4e')}, 'model': 'msl420 2.0.0', 'sw_version': '2.1.11', 'via_device': None} for 'meross_lan' config entry: device info needs to either describe a device, link to existing device or provide extra information.) in DeviceRegistry.async_get_or_create
```

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/meross_lan/meross_device.py:471
Integration: Meross LAN (documentation, issues)
First occurred: 1:35:55 PM (4 occurrences)
Last logged: 1:37:14 PM

Error setting up entry Microwave (mss310) for meross_lan
Error setting up entry msl420 2005289271243390814348e1e91d8f3c for meross_lan
Error setting up entry Kitchen Smart Light (msl420) for meross_lan
Traceback (most recent call last):
  File "/config/custom_components/meross_lan/helpers.py", line 586, in exception_warning
    yield
  File "/config/custom_components/meross_lan/meross_device.py", line 183, in __init__
    device_registry.async_get(ApiProfile.hass).async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 511, in async_get_or_create
    device_info_type = _validate_device_info(config_entry, device_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 165, in _validate_device_info
    raise DeviceInfoError(
homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'connections': {('mac', '48:e1:e9:22:70:98')}, 'default_manufacturer': 'Meross', 'default_name': 'Smart Plug (20062974313169251h5048e1e9227098)', 'identifiers': {('meross_lan', '20062974313169251h5048e1e9227098')}, 'model': 'mss310 2.0.0', 'sw_version': '2.1.16', 'via_device': None} for 'meross_lan' config entry: device info needs to either describe a device, link to existing device or provide extra information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/__init__.py", line 516, in async_setup_entry
    device = api.build_device(config_entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/__init__.py", line 402, in build_device
    device = class_type(descriptor, config_entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/switch.py", line 50, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/sensor.py", line 331, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/sensor.py", line 500, in __init__
    super().__init__(descriptor, entry)
  File "/config/custom_components/meross_lan/meross_device.py", line 351, in __init__
    super().__init__(
  File "/config/custom_components/meross_lan/meross_device.py", line 181, in __init__
    with self.exception_warning("DeviceRegistry.async_get_or_create"):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/config/custom_components/meross_lan/helpers.py", line 588, in exception_warning
    self.warning(
  File "/config/custom_components/meross_lan/meross_device.py", line 471, in warning
    if self._trace_file:
       ^^^^^^^^^^^^^^^^
AttributeError: 'ToggleXMixinElectricityMixinConsumptionMixinMerossDevice' object has no attribute '_trace_file'
```

**Comment by townsmcp** [comment]
Thank you @krahabb this is working for me after updating

**Comment by PV-Joe** [comment]
Home Assistant 2023.8 final broke Meross LAN for me as well. Hoping for a solution.

**Comment by thomsy81** [comment]
> Home Assistant 2023.8 final broke Meross LAN for me as well. Hoping for a solution.

Update the custom component that should fix it.

**Comment by PV-Joe** [comment]
> > Home Assistant 2023.8 final broke Meross LAN for me as well. Hoping for a solution.
> 
> Update the custom component that should fix it.

Thank you for replying so fast 😄

I deleted the Meross LAN integration and reinstalled and reconfigured it.

It sill shows the same issue:

![IMG_4059](https://github.com/krahabb/meross_lan/assets/110498562/fcf50daa-c052-4285-83ec-70442b8b552a)

![IMG_4058](https://github.com/krahabb/meross_lan/assets/110498562/cc5f709f-abd7-41e1-baed-4951c0324d0c)

Do I have to do anything else to update it?

**Comment by townsmcp** [comment]
@PV-Joe you need to UPDATE the component from HACS, not just remove and readd the same components from Settings

**Comment by PV-Joe** [comment]
> @PV-Joe you need to UPDATE the component from HACS, not just remove and readd the same components from Settings

Brillant suggestion!
I reinstalled from HACS and now Meross LAN is working with Home Assistant 2023.8.0 again 😄

i didn‘t realize there are two ways of installing the integration.

Thx for your fast response to my problem 👍
