### ISSUE TITLE
Smart Bulb MSL120da (FW 7.2.8) brightness control issue

### ISSUE THREAD

**Issue by kgbalphabeta** [krahabb/meross_lan#550]
v5.4.2

## Configuration

Core 2023.11.0
Supervisor 2025.04.0
Operating System 10.1

## Describe the bug
Brightness control not working with v5.4.2. Tried rolling back to older versions and same result. 
I suspect this started when Meross MSL120da FW update to FW 7.2.8

## Debug log

This error originated from a custom integration.

Logger: custom_components.meross_lan.msl120da_###############################2
Source: custom_components/meross_lan/helpers/__init__.py:290
Integration: Meross LAN (documentation, issues)
First occurred: 8:54:22 AM (1 occurrences)
Last logged: 8:54:22 AM

MLLight(0): AttributeError(module 'homeassistant.util.color' has no attribute 'value_to_brightness') in parsing light ({'capacity': 6, 'channel': 0, 'rgb': 16774144, 'temperature': 25, 'luminance': 58, 'transform': 0})

**Comment by krahabb** [comment]
Hello @kgbalphabeta,
I guess the problem lies in your HA core version being too old.
Currently, compatibility with older versions is being 'lazily' ensured since many features under development are only tested with current versions and so might hit a problem when running on previous HA cores.

If I don't miss anything, current release of meross_lan should be compatible with cores back to 2024.01 but I'm not really sure since I cannot reliably test the code against every single past release.

I'm not sure I can patch the code to run with that core (2023.11.0) since there might be other compatibility breaks in other parts of the code and it would be a lot of work to do and check
