### ISSUE TITLE
Error after upgrading to 2021.8.0

### ISSUE THREAD

**Issue by Ameglialuna** [krahabb/meross_lan#52]
After upgrading  to the 2021.08 version I have these errors in the log:

**ERROR (MainThread) [homeassistant.setup] Setup failed for meross_lan: Unable to import component: cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)**

**ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration meross_lan: cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)**

and the component doesn't work anymore

**Comment by Dio55** [comment]
> After upgrading to the 2021.08 version I have these errors in the log:
> 
> **ERROR (MainThread) [homeassistant.setup] Setup failed for meross_lan: Unable to import component: cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)**
> 
> **ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration meross_lan: cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)**
> 
> and the component doesn't work anymore

Same problem here ...

**Comment by drako86** [comment]
same problem whit my HA config

**Comment by larod241** [comment]
Same Here after 2021.08

**Comment by BeyondPixels** [comment]
Yep, same here after updating to HA OS 6.2 / core-2021.8.0

**Comment by SamboyCoding** [comment]
From what I can see these have changed as follows in 2021.8:
`ELECTRICAL_CURRENT_AMPERE` -> `ELECTRIC_CURRENT_AMPERE`
`VOLT` -> `ELECTRIC_POTENTIAL_VOLT`

Making these changes in my local copy of meross_entity.py (two occurrences of each) fixed it.

**Comment by larod241** [comment]
> From what I can see these have changed as follows in 2021.8:
> `ELECTRICAL_CURRENT_AMPERE` -> `ELECTRIC_CURRENT_AMPERE`
> `VOLT` -> `ELECTRIC_POTENTIAL_VOLT`
> 
> Making these changes in my local copy of meross_entity.py (two occurrences of each) fixed it.

Thks, it's work again after your suggest changes

**Comment by drako86** [comment]
> From what I can see these have changed as follows in 2021.8:
> `ELECTRICAL_CURRENT_AMPERE` -> `ELECTRIC_CURRENT_AMPERE`
> `VOLT` -> `ELECTRIC_POTENTIAL_VOLT`
> 
> Making these changes in my local copy of meross_entity.py (two occurrences of each) fixed it.

Thk it’s work again for me ^^

**Comment by krahabb** [comment]
Hello everybody,
Thank you for signaling and already 'fixing' this awful issue with core update.
I'm aware of this since this afternoon and I'm sorry  I can't fix it rightaway. I'll patch it likely tomorrow with some other queued minor features.
Thank you!

**Comment by Keltere** [comment]
Made a pull request with the fix https://github.com/krahabb/meross_lan/pull/53
