### ISSUE TITLE
AttributeError for mts215b

### ISSUE THREAD

**Issue by q8jmnpgrcc-pixel** [krahabb/meross_lan#612]
I received the following warning after upgrading HomeAssistant to 2025.12.0

This is the first version where I got that warning. The last version without warning was 2025.11.3

The version of the Meross Lan integration is:  5.7.1

Logger: custom_components.meross_lan.mts215b_###############################6
Quelle: custom_components/meross_lan/helpers/__init__.py:174
Integration: Meross LAN (Dokumentation, Probleme)
Erstmals aufgetreten: 03:30:00 (1 Vorkommnis)
Zuletzt protokolliert: 03:30:00

AttributeError('function' object has no attribute 'startswith') in loading digest initializer for key 'thermostat'

**Comment by krahabb** [comment]
I cannot reproduce the error, maybe something got corrupted, either the configuration or the meross_lan component installation files...

You could try uploading a device 'diagnostic' so that I could maybe spot something unusual in your configuration/device
